manifest:
  remotes:
    - name: jrsharp-zmk
      url-base: https://github.com/jrsharp
  projects:
    - name: zmk
      remote: jrsharp-zmk
      revision: main
      import: app/west.yml
  self:
    path: config
